networks:
  lab-network:

services:

  postgres:
    networks: lab-network
    image: postgres:16
    restart: unless-stopped

    container_name: postgres

    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword
      POSTGRES_DB: ticketdb

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labuser"]
      interval: 30s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    networks: lab-network

    image: redis:7
    restart: unless-stopped

    container_name: redis

    ports:
      - "6379:6379"

  app:
    networks: lab-network

    build:
      context: ./app

    container_name: flask-app
    restart: unless-stopped

    environment:
      DB_HOST: postgres
      DB_NAME: ticketdb
      DB_USER: labuser
      DB_PASSWORD: labpassword
      REDIS_HOST: redis

    ports:
      - "5000:5000"

    depends_on:
      - postgres
      - redis

  nginx:
    networks: lab-network

    image: nginx:latest
    restart: unless-stopped

    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

  prometheus:
    networks: lab-network

    image: prom/prometheus
    restart: unless-stopped

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    networks: lab-network

    image: grafana/grafana
    restart: unless-stopped

    container_name: grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123

    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    networks: lab-network

    image: grafana/loki:latest
    restart: unless-stopped

    container_name: loki

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/config.yml

    volumes:
      - ./loki/config.yml:/etc/loki/config.yml

  promtail:
    networks: lab-network

    image: grafana/promtail:latest
    restart: unless-stopped

    container_name: promtail

    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml

    command: -config.file=/etc/promtail/config.yml

  alertmanager:
    networks: lab-network

    image: prom/alertmanager
    restart: unless-stopped

    container_name: alertmanager

    ports:
      - "9093:9093"

    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  node-exporter:
    networks: lab-network

    image: prom/node-exporter
    restart: unless-stopped

    container_name: node-exporter

    ports:
      - "9100:9100"

  evaluator:
    networks: lab-network

    build:
      context: ./evaluator

    container_name: evaluator
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
  loki_data:
