{
 "title": "Docker Lab / Service Overview",
 "tags": [
  "docker-lab",
  "sre"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Ticket App Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ticket_app\"}"
    }
   ]
  },
  {
   "title": "Inventory App Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"inventory_app\"}"
    }
   ]
  },
  {
   "title": "Open Tickets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ticket_open_total" }
   ]
  },
  {
   "title": "SLA Breaches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ticket_sla_breached_total" }
   ]
  },
  {
   "title": "Inventory Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(inventory_http_requests_total[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Inventory p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint) (rate(inventory_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"docker_lab\"}"
    }
   ]
  }
 ]
}